import React, { useState } from 'react';
import { useParallax } from '@/contexts/ParallaxContext';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { 
  FileText, 
  Download, 
  Copy, 
  Check, 
  Sparkles, 
  Share2, 
  Printer, 
  ShieldCheck,
  CheckSquare,
  Square
} from 'lucide-react';
import { toast } from 'sonner';

export const IntelligenceReportView: React.FC = () => {
  const { intelligenceReportData, toggleReportSection, runPrompt, isGenerating } = useParallax();
  const [copied, setCopied] = useState(false);

  if (!intelligenceReportData) {
    return (
      <div className="p-8 text-center border border-dashed border-border rounded-xl">
        <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-3 opacity-40" />
        <h3 className="font-serif text-lg font-bold mb-2">No Intelligence Dossier Compiled</h3>
        <p className="text-sm text-muted-foreground max-w-md mx-auto mb-4">
          Aggregate findings, conflict analyses, assumption audits, and red-team findings into an executive intelligence report.
        </p>
        <Button onClick={() => runPrompt()} disabled={isGenerating}>
          <Sparkles className="w-4 h-4 mr-2" />
          Compile Intelligence Report
        </Button>
      </div>
    );
  }

  const enabledSections = intelligenceReportData.sections.filter(s => s.enabled);

  const getFullMarkdown = () => {
    return `# ${intelligenceReportData.title}\n**Dossier**: ${intelligenceReportData.dossierNumber} | **Classification**: ${intelligenceReportData.classification}\n**Date**: ${new Date(intelligenceReportData.generatedAt).toLocaleDateString()}\n\n## Executive Summary\n${intelligenceReportData.executiveSummary}\n\n## Key Findings\n${intelligenceReportData.keyFindings.map(f => `- ${f}`).join('\n')}\n\n${enabledSections.map(s => `${s.content}`).join('\n\n---\n\n')}\n\n---\n*Generated by PARALLAX AI Decision & Intelligence Laboratory*`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(getFullMarkdown());
    setCopied(true);
    toast.success('Complete Intelligence Dossier copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = () => {
    // Print dialog formatted as PDF export
    window.print();
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(intelligenceReportData, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `${intelligenceReportData.dossierNumber}_dossier.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    toast.success('Exported JSON Intelligence payload');
  };

  return (
    <div className="space-y-6 animate-in fade-in-50 duration-300">
      {/* Header & Export Actions */}
      <div className="p-4 rounded-xl bg-card border border-border flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Badge className="font-mono text-xs uppercase bg-primary text-primary-foreground">
              {intelligenceReportData.classification}
            </Badge>
            <span className="font-mono text-xs text-muted-foreground">{intelligenceReportData.dossierNumber}</span>
          </div>
          <h2 className="font-serif text-xl md:text-2xl font-bold tracking-tight text-foreground">
            {intelligenceReportData.title}
          </h2>
          <p className="text-xs font-mono text-muted-foreground mt-0.5">
            Compiled on {new Date(intelligenceReportData.generatedAt).toLocaleString()} • Multi-Model Triangulation Verified
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleCopyMarkdown} className="text-xs">
            {copied ? <Check className="w-3.5 h-3.5 mr-1.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 mr-1.5" />}
            Copy Markdown
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownloadJSON} className="text-xs">
            <Download className="w-3.5 h-3.5 mr-1.5" />
            JSON
          </Button>
          <Button size="sm" onClick={handleDownloadPDF} className="text-xs">
            <Printer className="w-3.5 h-3.5 mr-1.5" />
            Export PDF Dossier
          </Button>
        </div>
      </div>

      {/* Section Inclusion Toggle Bar */}
      <div className="p-3 rounded-lg bg-muted/20 border border-border flex flex-wrap items-center gap-2 text-xs">
        <span className="font-mono text-muted-foreground mr-1">Include Sections:</span>
        {intelligenceReportData.sections.map(sec => (
          <Button
            key={sec.id}
            variant={sec.enabled ? 'secondary' : 'ghost'}
            size="sm"
            onClick={() => toggleReportSection(sec.id)}
            className="h-6 text-[11px] px-2 font-mono flex items-center gap-1"
          >
            {sec.enabled ? <CheckSquare className="w-3 h-3 text-primary" /> : <Square className="w-3 h-3 text-muted-foreground" />}
            {sec.title.split('.')[1] || sec.title}
          </Button>
        ))}
      </div>

      {/* Document Reader Layout (Editorial Dossier Style) */}
      <Card className="border-border bg-card shadow-sm">
        <CardHeader className="border-b border-border/60 pb-6">
          <div className="flex justify-between items-start text-xs font-mono text-muted-foreground mb-4">
            <span>PARALLAX AI DECISION LABORATORY</span>
            <span>STRATEGIC BRIEFING</span>
          </div>

          <CardTitle className="text-2xl font-serif font-bold text-foreground">
            {intelligenceReportData.title}
          </CardTitle>

          {/* Key Findings Callout */}
          <div className="p-4 rounded-lg bg-primary/[0.04] border border-primary/20 space-y-2 mt-4 text-xs">
            <strong className="text-primary block font-mono text-xs uppercase tracking-wider">
              Core Executive Findings:
            </strong>
            <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 text-foreground/90">
              {intelligenceReportData.keyFindings.map((kf, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <ShieldCheck className="w-3.5 h-3.5 text-primary shrink-0 mt-0.5" />
                  <span>{kf}</span>
                </li>
              ))}
            </ul>
          </div>
        </CardHeader>

        <CardContent className="p-6 md:p-8 space-y-8 text-sm leading-relaxed">
          {enabledSections.map(section => (
            <div key={section.id} className="space-y-3">
              <h3 className="font-serif text-lg font-bold text-foreground border-b border-border/40 pb-2">
                {section.title}
              </h3>
              <div className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground whitespace-pre-wrap">
                {section.content}
              </div>
            </div>
          ))}
        </CardContent>

        <CardFooter className="border-t border-border/60 p-4 bg-muted/10 flex items-center justify-between text-xs font-mono text-muted-foreground">
          <span>CLASSIFICATION: {intelligenceReportData.classification}</span>
          <span>PARALLAX • A Curio Network product</span>
        </CardFooter>
      </Card>
    </div>
  );
};
