import { AIModel } from '@/types/parallax';

export const AVAILABLE_TEXT_MODELS: AIModel[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o Omnimodal',
    provider: 'OpenAI',
    providerCode: 'openai',
    version: '2024-11-20',
    description: 'Flagship omnimodal model combining broad factual grounding, rigorous reasoning, and rapid token generation.',
    capabilities: ['Reasoning', 'Writing', 'Coding', 'Research', 'Vision', 'Fast Response'],
    speedRating: 'Fast',
    latencyEstimateMs: 980,
    contextWindow: '128k tokens',
    costPer1kTokens: '$0.0050',
    isVisionCapable: true,
    available: true,
    accentColor: '#10A37F',
    strengths: ['Versatile structured outputs', 'Concise synthesis', 'Strong instruction following'],
    weaknesses: ['Can be overly eager to agree', 'Cautious on edge cases'],
  },
  {
    id: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet',
    provider: 'Anthropic',
    providerCode: 'anthropic',
    version: '3.7 Extended Thinking',
    description: 'Premier hybrid reasoning architecture with adjustable cognitive depth, superior prose elegance, and profound nuance.',
    capabilities: ['Reasoning', 'Writing', 'Coding', 'Research', 'Vision'],
    speedRating: 'Balanced',
    latencyEstimateMs: 1450,
    contextWindow: '200k tokens',
    costPer1kTokens: '$0.0060',
    isVisionCapable: true,
    isReasoningSpecialist: true,
    available: true,
    accentColor: '#D97706',
    strengths: ['Exceptional nuance & tone', 'Transparent reasoning steps', 'Refusal calibration'],
    weaknesses: ['Slightly higher generation latency on complex chains'],
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google DeepMind',
    providerCode: 'google',
    version: '2.5 Flash / Pro Multimodal',
    description: 'Deep analytical model with real-time web grounding capability, expansive million-token context, and mathematical precision.',
    capabilities: ['Reasoning', 'Research', 'Coding', 'Vision', 'Fast Response'],
    speedRating: 'Fast',
    latencyEstimateMs: 1120,
    contextWindow: '1M tokens',
    costPer1kTokens: '$0.0035',
    isVisionCapable: true,
    available: true,
    accentColor: '#2563EB',
    strengths: ['Live web knowledge retrieval', 'Deep document scanning', 'Cross-modal citations'],
    weaknesses: ['Stylistic variation can be dry in narrative contexts'],
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek AI',
    providerCode: 'deepseek',
    version: 'R1-Full (Reasoning)',
    description: 'Open-weight reinforcement-learning reasoning titan with chain-of-thought introspection for math, logic, and code proof.',
    capabilities: ['Reasoning', 'Coding', 'Research'],
    speedRating: 'Deep/Thinking',
    latencyEstimateMs: 2100,
    contextWindow: '64k tokens',
    costPer1kTokens: '$0.0014',
    isReasoningSpecialist: true,
    available: true,
    accentColor: '#4F46E5',
    strengths: ['Unvarnished rigorous logic proofs', 'Exhaustive verification', 'Low cost'],
    weaknesses: ['Verbose chain of thought', 'No native image generation'],
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B Instruct',
    provider: 'Meta AI',
    providerCode: 'meta',
    version: '3.3-70B-Instruct',
    description: 'High-throughput open-standard intelligence tuned for high alignment accuracy, direct answers, and structural clarity.',
    capabilities: ['Writing', 'Reasoning', 'Coding', 'Fast Response'],
    speedRating: 'Ultra Fast',
    latencyEstimateMs: 650,
    contextWindow: '128k tokens',
    costPer1kTokens: '$0.0008',
    available: true,
    accentColor: '#0668E1',
    strengths: ['Lightning fast execution', 'Unopinionated neutral delivery', 'Standard compliance'],
    weaknesses: ['Slightly lower depth on multi-hop logical deductions'],
  },
];

export const AVAILABLE_IMAGE_MODELS: AIModel[] = [
  {
    id: 'kling-omni-v1',
    name: 'Kling Omni-Image Pro',
    provider: 'Kling AI',
    providerCode: 'kling',
    version: 'Omni 2.0',
    description: 'High-fidelity cinematic generative visual model with remarkable atmospheric lighting and anatomical coherence.',
    capabilities: ['Image Generation', 'Vision', 'Fast Response'],
    speedRating: 'Fast',
    latencyEstimateMs: 2400,
    contextWindow: 'N/A',
    costPer1kTokens: '$0.02 / img',
    isImageCapable: true,
    available: true,
    accentColor: '#EC4899',
    strengths: ['Cinematic depth & lighting', 'Complex composition rendering', 'Asian & global aesthetics'],
    weaknesses: ['Strict text formatting inside images'],
  },
  {
    id: 'dall-e-3',
    name: 'DALL·E 3 High-Def',
    provider: 'OpenAI',
    providerCode: 'openai',
    version: '3.0 HD',
    description: 'Semantic fidelity powerhouse with deep prompt comprehension, typography adherence, and vivid concept synthesis.',
    capabilities: ['Image Generation'],
    speedRating: 'Balanced',
    latencyEstimateMs: 3100,
    contextWindow: 'N/A',
    costPer1kTokens: '$0.04 / img',
    isImageCapable: true,
    available: true,
    accentColor: '#10A37F',
    strengths: ['Prompt adherence precision', 'Legible text rendering', 'Complex multi-subject layouts'],
    weaknesses: ['Can over-polish photographic realism'],
  },
  {
    id: 'flux-1-pro',
    name: 'Flux.1 Pro',
    provider: 'Black Forest Labs',
    providerCode: 'black-forest',
    version: '1.0 Pro',
    description: 'Next-generation flow-matching image engine with exceptional tactile photorealism and fine-grained texture resolution.',
    capabilities: ['Image Generation'],
    speedRating: 'Balanced',
    latencyEstimateMs: 2800,
    contextWindow: 'N/A',
    costPer1kTokens: '$0.03 / img',
    isImageCapable: true,
    available: true,
    accentColor: '#F59E0B',
    strengths: ['Micro-texture detail & skin tones', 'Dynamic range & natural shadows', 'Artistic style flexibility'],
    weaknesses: ['Requires descriptive camera/lighting prompts for best results'],
  },
  {
    id: 'midjourney-v6',
    name: 'Midjourney v6.1 Refined',
    provider: 'Midjourney',
    providerCode: 'midjourney',
    version: 'v6.1',
    description: 'Editorial grade visual stylization engine favored by concept artists, art directors, and editorial publishers.',
    capabilities: ['Image Generation'],
    speedRating: 'Balanced',
    latencyEstimateMs: 3400,
    contextWindow: 'N/A',
    costPer1kTokens: '$0.035 / img',
    isImageCapable: true,
    available: true,
    accentColor: '#8B5CF6',
    strengths: ['Poetic lighting', 'Editorial polish', 'Unrivaled aesthetic coherence'],
    weaknesses: ['Occasional hallucination of background details'],
  },
];

export const ALL_MODELS = [...AVAILABLE_TEXT_MODELS, ...AVAILABLE_IMAGE_MODELS];

export const DEFAULT_SELECTED_TEXT_MODELS = ['gpt-4o', 'claude-3-7-sonnet', 'gemini-2.5-pro', 'deepseek-r1'];
export const DEFAULT_SELECTED_IMAGE_MODELS = ['kling-omni-v1', 'dall-e-3', 'flux-1-pro', 'midjourney-v6'];

export function getModelById(id: string): AIModel | undefined {
  return ALL_MODELS.find(m => m.id === id);
}
